# Generated by Django 4.2 on 2025-10-19 22:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', django_mysql.models.EnumField(choices=[('PROGRAMADO', 'PROGRAMADO'), ('COMPPLETADO', 'COMPPLETADO'), ('CANC', 'CANC')], default='PROGRAMADO')),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=250)),
                ('observaciones', models.CharField(blank=True, max_length=250)),
            ],
            options={
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('direccion', models.CharField(blank=True, max_length=100)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', django_mysql.models.EnumField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('VETERINARIO', 'VETERINARIO'), ('RECEPCIONISTA', 'RECEPCIONISTA'), ('CLIENTE', 'CLIENTE')], default='CLIENTE')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__username'],
            },
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('especialidad', models.CharField(max_length=100)),
                ('licencia_profesional', models.CharField(max_length=100, unique=True)),
                ('telefono_laboral', models.CharField(blank=True, max_length=15)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='veterinario', to='app.perfil')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', django_mysql.models.EnumField(choices=[('PERRO', 'PERRO'), ('GATO', 'GATO'), ('CONEJO', 'CONEJO'), ('AVE', 'AVE'), ('OTRO', 'OTRO')])),
                ('sexo', django_mysql.models.EnumField(choices=[('M', 'M'), ('F', 'F')])),
                ('nombre', models.CharField(max_length=45)),
                ('raza', models.CharField(blank=True, max_length=45)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=45)),
                ('activo', models.BooleanField(default=True)),
                ('dueno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mascotas', to='app.cliente')),
            ],
            options={
                'ordering': ['dueno__apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('diagnostico', models.CharField(max_length=250)),
                ('tratamiento', models.CharField(blank=True, max_length=250)),
                ('medicamentos', models.CharField(blank=True, max_length=250)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='app.cita')),
            ],
            options={
                'ordering': ['-fecha_consulta'],
            },
        ),
        migrations.AddField(
            model_name='cliente',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to='app.perfil'),
        ),
        migrations.AddField(
            model_name='cita',
            name='mascota',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='app.mascota'),
        ),
        migrations.AddField(
            model_name='cita',
            name='veterinario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='citas', to='app.veterinario'),
        ),
        migrations.AddIndex(
            model_name='cita',
            index=models.Index(fields=['fecha_hora'], name='app_cita_fecha_h_daaca8_idx'),
        ),
    ]
