# Generated by Django 4.2 on 2025-10-21 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_perfil_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recepcionista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono_laboral', models.CharField(blank=True, max_length=15)),
                ('extension', models.CharField(blank=True, max_length=10)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recepcionista', to='app.perfil')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
    ]
