# Generated by Django 4.2 on 2025-10-21 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_recepcionista'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recepcionista',
        ),
    ]
