# Generated by Django 4.2 on 2025-10-22 17:33

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_recepcionista'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=django_mysql.models.EnumField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('VETERINARIO', 'VETERINARIO'), ('ls', 'ls'), ('CLIENTE', 'CLIENTE')], default='CLIENTE'),
        ),
    ]
