# Generated by Django 4.2 on 2025-10-23 03:37

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_perfil_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='tipo',
            field=django_mysql.models.EnumField(choices=[('ADMINISTRADOR', 'ADMINISTRADOR'), ('VETERINARIO', 'VETERINARIO'), ('RECEPCIONISTA', 'RECEPCIONISTA'), ('CLIENTE', 'CLIENTE')], default='CLIENTE'),
        ),
    ]
