# Generated by Django 4.2 on 2025-10-25 21:32

from django.db import migrations
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_perfil_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=django_mysql.models.EnumField(choices=[('PROGRAMADO', 'PROGRAMADO'), ('COMPLETADO', 'COMPLETADO'), ('CANCELADO', 'CANCELADO')], default='PROGRAMADO'),
        ),
    ]
