# Generated by Django 4.2 on 2025-10-27 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_cita_estado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cita',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cita',
            name='app_cita_fecha_h_daaca8_idx',
        ),
    ]
