# Generated by Django 4.2 on 2025-10-28 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_cita_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veterinario',
            name='licencia_profesional',
            field=models.CharField(max_length=100),
        ),
    ]
